repos:
  - repo: local
    hooks:
      - id: prettier
        name: Format with Prettier
        entry: bunx prettier --write
        language: system
        files: \.(js|ts|svelte|json|md|yml|yaml)$
        pass_filenames: true

      - id: eslint
        name: Lint with ESLint
        entry: bunx eslint --fix
        language: system
        files: \.(js|ts|svelte)$
        pass_filenames: true

      - id: svelte-check
        name: Type check with svelte-check
        entry: bun run check
        language: system
        files: \.(js|ts|svelte)$
        pass_filenames: false
