name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SKIP_INSTALL_SIMPLE_HOOKS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bun run format:check

      - name: Sync SvelteKit
        run: bunx svelte-kit sync

      - name: Lint and type check
        run: bun run lint

      - name: Build application
        run: bun --bun run build

      - name: Run tests (if any)
        run: |
          if [ -f "bun.lockb" ] && bun test --help >/dev/null 2>&1; then
            bun test --coverage
          else
            echo "No tests found, skipping test step"
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
